# Modern Dart lints for best practices.
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat dead code as warnings
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "build/**"

linter:
  rules:
    # Enforce public API documentation
    public_member_api_docs: false # Enable later when docs are complete
    # Prefer const constructors
    prefer_const_constructors: true
    prefer_const_declarations: true
    # Avoid unnecessary null checks
    avoid_null_checks_in_equality_operators: true
    # Use final for local variables
    prefer_final_locals: true
    # Prefer single quotes
    prefer_single_quotes: true
    # Avoid print statements in production code
    avoid_print: false # We use logger service instead
    # Type annotations
    always_declare_return_types: true
    # Prefer expression functions
    prefer_expression_function_bodies: false
